=== 0xaldric/indexer/abi/abi.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://tvm.sh/abi.schema.json",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "interface_name": {
        "type": "string",
        "pattern": "^([a-z0-9_]+)$"
      },
      "addresses": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "definitions": {
        "type": "object",
        "patternProperties": {
          "^([a-z0-9_]+)\\.([a-z0-9_]+)\\.([a-z0-9_]+)$": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/tlb_value"
            }
          }
        }
      },
      "code_boc": {
        "type": "string"
      },
      "get_methods": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "arguments": {
              "type": "array",
              "items": {
                "$ref": "#/$defs/vm_value"
              }
            },
            "return_values": {
              "type": "array",
              "items": {
                "$ref": "#/$defs/vm_value"
              }
            }
          },
          "required": [
            "name",
            "return_values"
          ],
          "additionalProperties": false
        }
      },
      "in_messages": {
        "type": "array",
        "items": {
          "$ref": "#/$defs/message"
        }
      },
      "out_messages": {
        "type": "array",
        "items": {
          "$ref": "#/$defs/message"
        }
      }
    },
    "required": [
      "interface_name"
    ],
    "additionalProperties": false
  },
  "$defs": {
    "vm_value": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "stack_type": {
          "enum": [
            "int",
            "cell",
            "slice"
          ]
        },
        "format": {
          "enum": [
            "bigInt",
            "uint8",
            "uint16",
            "uint32",
            "uint64",
            "int8",
            "int16",
            "int32",
            "int64",
            "bool",
            "bytes",
            "cell",
            "slice",
            "string",
            "addr",
            "content",
            "struct",
            "asset",
            "dedustAsset"
          ]
        },
        "struct_fields": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/tlb_value"
          }
        }
      },
      "required": [
        "name",
        "stack_type"
      ]
    },
    "tlb_value": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "pattern": "^[a-z0-9_]+$"
        },
        "tlb_type": {
          "oneOf": [
            {
              "enum": [
                ".",
                "^",
                "bool",
                "addr"
              ]
            },
            {
              "type": "string",
              "pattern": "^#[a-f0-9]+$"
            },
            {
              "type": "string",
              "pattern": "^\\[[^\\]]+\\]$"
            },
            {
              "type": "string",
              "pattern": "^\\$[01]+$"
            },
            {
              "type": "string",
              "pattern": "^(##|bits) \\d{1,3}$"
            },
            {
              "type": "string",
              "pattern": "^maybe (\\^)$"
            },
            {
              "type": "string",
              "pattern": "^either ([\\^.]) ([\\^.])$"
            }
          ]
        },
        "format": {
          "enum": [
            "bool",
            "int8",
            "int16",
            "int32",
            "int64",
            "uint8",
            "uint16",
            "uint32",
            "uint64",
            "bigInt",
            "coins",
            "bytes",
            "string",
            "addr",
            "cell",
            "dict",
            "tag",
            "telemintText",
            "asset",
            "struct",
            "dedustAsset"
          ]
        },
        "struct_fields": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/tlb_value"
          }
        },
        "optional": {
          "type": "boolean"
        }
      },
      "required": [
        "name",
        "tlb_type"
      ],
      "additionalProperties": false
    },
    "message": {
      "type": "object",
      "properties": {
        "op_name": {
          "type": "string"
        },
        "op_code": {
          "type": "string",
          "pattern": "^0x([0-9a-f]{1,8})$"
        },
        "type": {
          "enum": [
            "INTERNAL",
            "EXTERNAL_IN",
            "EXTERNAL_OUT",
            "internal",
            "external_in",
            "external_out"
          ]
        },
        "body": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/tlb_value"
          }
        }
      },
      "required": [
        "op_name",
        "op_code"
      ],
      "additionalProperties": false
    }
  }
}

=== 0xaldric/indexer/abi/known/multi_token_pool.json
[
	{
		"interface_name": "multi-token-pool",
		"addresses": ["kQAlSBe3Xs1E9vuUscYKZbpjxIjyIBWqUnYT9_QBjwRn1Knd"],
		"definitions": {},
		"get_methods": [],
		"in_messages": [],
		"out_messages": [
			{
				"op_name": "create_pool_success",
				"op_code": "0xef12c3d4",
				"type": "external_out",
				"body": [
					{
						"name": "data",
						"tlb_type": "^",
						"format": "struct",
						"struct_fields": [
							{
								"name": "user_address",
								"tlb_type": "addr",
								"format": "addr"
							},
							{
								"name": "pool_key",
								"tlb_type": "## 256",
								"format": "bigInt"
							},
							{
								"name": "tokens_in",
								"tlb_type": "^"
							},
							{
								"name": "tokens_dict",
								"tlb_type": "^"
							}
						]
					}
				]
			},
			{
				"op_name": "provide_liquidity_success",
				"op_code": "0xb5f82f3c",
				"type": "external_out",
				"body": [
					{
						"name": "data",
						"tlb_type": "^",
						"format": "struct",
						"struct_fields": [
							{
								"name": "user_address",
								"tlb_type": "addr",
								"format": "addr"
							},
							{
								"name": "pool_key",
								"tlb_type": "## 256",
								"format": "bigInt"
							},
							{
								"name": "tokens_in",
								"tlb_type": "^"
							},
							{
								"name": "tokens_dict",
								"tlb_type": "^"
							}
						]
					}
				]
			},
			{
				"op_name": "remove_liquidity_success",
				"op_code": "0xb03abb18",
				"type": "external_out",
				"body": [
					{
						"name": "data",
						"tlb_type": "^",
						"format": "struct",
						"struct_fields": [
							{
								"name": "user_address",
								"tlb_type": "addr",
								"format": "addr"
							},
							{
								"name": "pool_key",
								"tlb_type": "## 256",
								"format": "bigInt"
							},
							{
								"name": "tokens_in",
								"tlb_type": "^"
							},
							{
								"name": "tokens_dict",
								"tlb_type": "^"
							}
						]
					}
				]
			},
			{
				"op_name": "swap_success",
				"op_code": "0x7dd7fca3",
				"type": "external_out",
				"body": [
					{
						"name": "data",
						"tlb_type": "^",
						"format": "struct",
						"struct_fields": [
							{
								"name": "user_address",
								"tlb_type": "addr",
								"format": "addr"
							},
							{
								"name": "to_address",
								"tlb_type": "addr",
								"format": "addr"
							},
							{
								"name": "pool_key",
								"tlb_type": "## 256",
								"format": "bigInt"
							},
							{
								"name": "token_info",
								"tlb_type": "^"
							},
							{
								"name": "amount_info",
								"tlb_type": "^"
							},
							{
								"name": "tokens_dict",
								"tlb_type": "^"
							}
						]
					}
				]
			}
		]
	}
]
